### ISSUE TITLE
ZZTMMO - Funding

### ISSUE THREAD

**Issue by shotintoeternity** [Marak/zztmmo#6]
Hi, I wanted to talk to your team about potentially helping to fund the ZZTMMO project. I'm an old ZZTer and would love to try to get this off the ground. I was hoping to work with you on a Kickstarter to pay for things like development expenses.

Alternatively, I am also building a ZZT-based game right now and would be interested in paying someone on the team to help me develop it. Let me know if anyone on the repo might be interested in either project. Thanks!

Kevin
kevin@meshnetworkingllc.com

**Comment by Marak** [comment]
@shotintoeternity 

Hello. No one has worked on this in 9+ years.

I'm curious as how would you intend to fund a ZZT-based game without the rights to the game itself? I think it's owned by Tim Sweeney or Epic Games?

Feel free to email support@marak.com. Maybe I can help get you going in the right direction if you are starting a development effort.

**Comment by shotintoeternity** [comment]
Hey Marak, thanks again for your help with this and apologies for the late
response. I have a team of developers that I am working with to help create
the project and host what would hopefully be an online MMO version of ZZT
similar to your original project (ideally with playable historical ZZT
worlds). I'm sure that Tim Sweeney won't have a problem with it, just like
he hasn't had a problem with the rest of the developments in the fan
communities (MZX, ZZT 4.0, ZIG, etc.) over the years.

Even if the game isn't truly MMO, at least players would be able to start
their own server or go to our hosted site to play with/against each other.
I would be glad to get some other node.js developers working on the project
again if it's something you're interested in.

I think it's a really cool project and have for a long time, and there's
also a bonus of maybe being able to use elements of it in a piece of
multimedia art setting. Please let me know what you think and what the best
steps forward would be. Thanks!

**Comment by shotintoeternity** [comment]
Hi Marak, hope you're doing well and that you enjoyed the holidays! ZZT has
been having a resurgence over the last few years, and I'm still very
interested in the idea of adding multiplayer capability. The original
source code reconstruction for ZZT has been released as open source here:
https://github.com/asiekierka/reconstruction-of-super-zzt.

I would love to work with you on a project to create an MMO (or just
multiplayer) version of ZZT if you're interested. The Zeta project is also
available open source, and it might work well to use for development:
https://github.com/asiekierka/zeta/

I would be willing to raise funds for the creation of the project and have
money available for the initial project costs. What are your rates for
consulting?

Hope you're having a great 2023 so far, and talk to you soon!
